export const characters = [
  {
    name: "Hero",
    class: "Explorer",
    job: "Warrior",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Paladin",
    class: "Explorer",
    job: "Warrior",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Dark Knight",
    class: "Explorer",
    job: "Warrior",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Bishop",
    class: "Explorer",
    job: "Magician",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Arch Mage (I/L)",
    class: "Explorer",
    job: "Magician",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Arch Mage (F/P)",
    class: "Explorer",
    job: "Magician",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Dual Blade",
    class: "Explorer",
    job: "Thief",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Shadower",
    class: "Explorer",
    job: "Thief",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Night Lord",
    class: "Explorer",
    job: "Thief",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Pathfinder",
    class: "Explorer",
    job: "Thief",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Marksman",
    class: "Explorer",
    job: "Archer",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Bowmaster",
    class: "Explorer",
    job: "Archer",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Cannonneer",
    class: "Explorer",
    job: "Pirate",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Buccaneer",
    class: "Explorer",
    job: "Pirate",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Corsair",
    class: "Explorer",
    job: "Pirate",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Dawn Warrior",
    class: "Cygnus Knight",
    job: "Warrior",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Thunder Breaker",
    class: "Cygnus Knight",
    job: "Pirate",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Night Walker",
    class: "Cygnus Knight",
    job: "Thief",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Wind Archer",
    class: "Cygnus Knight",
    job: "Archer",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Blaze Wizard",
    class: "Cygnus Knight",
    job: "Magician",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Mihile",
    class: "Cygnus Knight",
    job: "Warrior",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Mercedes",
    class: "Hero",
    job: "Archer",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Aran",
    class: "Hero",
    job: "Warrior",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Phantom",
    class: "Hero",
    job: "Thief",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Luminous",
    class: "Hero",
    job: "Magician",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Evan",
    class: "Hero",
    job: "Magician",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Shade",
    class: "Hero",
    job: "Pirate",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Battle Mage",
    class: "Resistance",
    job: "Magician",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Blaster",
    class: "Resistance",
    job: "Warrior",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Mechanic",
    class: "Resistance",
    job: "Pirate",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Wild Hunter",
    class: "Resistance",
    job: "Archer",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Xenon",
    class: "Resistance",
    job: "Thief",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Demon Slayer",
    class: "Resistance",
    job: "Warrior",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Demon Avenger",
    class: "Resistance",
    job: "Warrior",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Angelic Buster",
    class: "Nova",
    job: "Pirate",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Kaiser",
    class: "Nova",
    job: "Warrior",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Cadena",
    class: "Nova",
    job: "Thief",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Kain",
    class: "Nova",
    job: "Archer",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Kanna",
    class: "Sengoku",
    job: "Magician",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Hayato",
    class: "Sengoku",
    job: "Warrior",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Adele",
    class: "Flora",
    job: "Warrior",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Ark",
    class: "Flora",
    job: "Pirate",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Illium",
    class: "Flora",
    job: "Magician",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Khali",
    class: "Flora",
    job: "Thief",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Hoyoung",
    class: "Anima",
    job: "Thief",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Lara",
    class: "Anima",
    job: "Magician",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Kinesis",
    class: "Other",
    job: "Magician",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Zero",
    class: "Other",
    job: "Warrior",
    level: 0,
    rank: null,
    grid: null,
  },
  {
    name: "Lynn",
    class: "Other",
    job: "Magician",
    level: 0,
    rank: null,
    grid: null,
  },
];
export const legionClass = [
  { class: "Archer", count: 0 },
  { class: "Magician", count: 0 },
  { class: "Pirate", count: 0 },
  { class: "Thief", count: 0 },
  { class: "Warrior", count: 0 },
];

export const legionRank = [
  { rank: "Unrank", min: 1, max: 59, zmin: 1, zmax: 129, count: 0 },
  { rank: "B", min: 60, max: 99, zmin: 130, zmax: 159, count: 0 },
  { rank: "A", min: 100, max: 139, zmin: 160, zmax: 179, count: 0 },
  { rank: "S", min: 140, max: 199, zmin: 180, zmax: 199, count: 0 },
  { rank: "SS", min: 200, max: 249, zmin: 200, zmax: 249, count: 0 },
  { rank: "SSS", min: 250, max: 300, zmin: 250, zmax: 300, count: 0 },
];

export const legionGrid = [
  {
    grid: "Lvl 60",
    baseRank: "B",
    jobSpecific: ["Warrior", "Archer", "Magician", "Thief", "Pirate"],
    nameSpecific: null,
    count: 0,
  },
  {
    grid: "Lvl 100",
    baseRank: "A",
    jobSpecific: ["Warrior", "Archer", "Magician", "Thief", "Pirate"],
    nameSpecific: null,
    count: 0,
  },
  {
    grid: "Lvl 140 Warrior/Pirate",
    baseRank: "S",
    jobSpecific: ["Warrior", "Pirate"],
    nameSpecific: null,
    count: 0,
  },
  {
    grid: "Lvl 140 Mage/Thief/Archer",
    baseRank: "S",
    jobSpecific: ["Magician", "Thief", "Archer"],
    nameSpecific: null,
    count: 0,
  },
  {
    grid: "Lvl 200 Warrior",
    baseRank: "SS",
    jobSpecific: ["Warrior"],
    nameSpecific: null,
    count: 0,
  },
  {
    grid: "Lvl 200 Archer",
    baseRank: "SS",
    jobSpecific: ["Archer"],
    nameSpecific: null,
    count: 0,
  },
  {
    grid: "Lvl 200 Thief",
    baseRank: "SS",
    jobSpecific: ["Thief"],
    nameSpecific: null,
    count: 0,
  },
  {
    grid: "Lvl 200 Magician",
    baseRank: "SS",
    jobSpecific: ["Magician"],
    nameSpecific: null,
    count: 0,
  },
  {
    grid: "Lvl 200 Pirate",
    baseRank: "SS",
    jobSpecific: ["Pirate"],
    nameSpecific: null,
    count: 0,
  },
  {
    grid: "Lvl 250 Warrior",
    baseRank: "SSS",
    jobSpecific: ["Warrior"],
    nameSpecific: null,
    count: 0,
  },
  {
    grid: "Lvl 250 Archer",
    baseRank: "SSS",
    jobSpecific: ["Archer"],
    nameSpecific: null,
    count: 0,
  },
  {
    grid: "Lvl 250 Thief",
    baseRank: "SSS",
    jobSpecific: ["Thief"],
    nameSpecific: null,
    count: 0,
  },
  {
    grid: "Lvl 250 Magician",
    baseRank: "SSS",
    jobSpecific: ["Magician"],
    nameSpecific: null,
    count: 0,
  },
  {
    grid: "Lvl 250 Pirate",
    baseRank: "SSS",
    jobSpecific: ["Pirate"],
    nameSpecific: null,
    count: 0,
  },
  {
    grid: "Lvl 250 Xenon",
    baseRank: "SSS",
    jobSpecific: [],
    nameSpecific: "Xenon",
    count: 0,
  },
];
